// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: 2026 Angel Careaga <hello@angelcareaga.com>

// MtProtoSessionPoolSmokeTest - LIVE acceptance test for the connection pool.
//
// This test intentionally reuses the auth key generated by the live
// handshake smoke. Opening a channel from existing per-DC auth material is
// the production path and avoids burning another 2048-bit DH handshake just
// to validate pool construction.

using System;
using System.Diagnostics;
using System.Globalization;
using System.Threading;
using System.Threading.Tasks;
using Vianigram.Kernel.Logging;

namespace Vianigram.SmokeTests.Tests
{
    public static class MtProtoSessionPoolSmokeTest
    {
        private static readonly TimeSpan TestTimeout = TimeSpan.FromSeconds(60);
        private static readonly TimeSpan OpenTimeout = TimeSpan.FromSeconds(15);
        private static readonly object ChannelGate = new object();

        private const int ExpectedDefaultPoolSize = 4;
        private const int ExpectedMinPoolSize = 1;

        private static global::Vianigram.MTProto.MtProtoChannel cachedChannel;
        private static ulong cachedAuthKeyId;

        public static async Task<TestEntry> RunAsync(CancellationToken ct)
        {
            var entry = new TestEntry
            {
                Suite = "Live",
                Name = "MTProto session pool open (DC #2)"
            };
            var sw = Stopwatch.StartNew();

            using (var cts = CancellationTokenSource.CreateLinkedTokenSource(ct))
            {
                cts.CancelAfter(TestTimeout);

                LiveAuthKeyMaterial key = null;
                global::Vianigram.MTProto.MtProtoChannel channel = null;
                bool keepChannelAlive = false;
                try
                {
                    LiveSmokeTestSupport.Diag(
                        "SessionPool RunAsync entry target=" +
                        LiveAuthKeyCache.TestDcHost + ":" +
                        LiveAuthKeyCache.TestDcPort);

                    key = await LiveAuthKeyCache.GetOrCreateAsync(
                        sw,
                        cts.Token,
                        "SessionPool").ConfigureAwait(false);

                    if (key == null || key.AuthKeyBytes == null ||
                        key.AuthKeyBytes.Length != 256)
                    {
                        entry.Passed = false;
                        entry.Detail = "Cached auth key material is invalid.";
                        return entry;
                    }

                    channel = TryGetCachedChannel(key.AuthKeyId);
                    if (channel != null)
                    {
                        keepChannelAlive = true;
                        PopulateSuccess(entry, channel, key, "memory");
                        return entry;
                    }

                    channel = await LiveSmokeTestSupport.AwaitAsync(
                        global::Vianigram.MTProto.MtProtoChannel
                            .OpenAsync(key.Host, key.Port,
                                       key.AuthKeyBytes, key.AuthKeyId,
                                       key.InitialServerSalt,
                                       key.ServerTimeOffset),
                        OpenTimeout,
                        "SessionPool MtProtoChannel.OpenAsync",
                        sw,
                        cts.Token,
                        delegate(global::Vianigram.MTProto.MtProtoChannel lateChannel)
                        {
                            if (lateChannel != null)
                                lateChannel.Close();
                        }).ConfigureAwait(false);

                    if (channel == null)
                    {
                        entry.Passed = false;
                        entry.Detail = "MtProtoChannel.OpenAsync returned null.";
                        return entry;
                    }

                    if (!IsValidChannel(channel))
                    {
                        entry.Passed = false;
                        entry.Detail = DescribeInvalidChannel(channel);
                        return entry;
                    }

                    CacheChannel(key.AuthKeyId, channel);
                    keepChannelAlive = true;
                    PopulateSuccess(entry, channel, key, "opened");
                    LiveSmokeTestSupport.Diag("SessionPool success " + entry.Detail);
                    return entry;
                }
                catch (TimeoutException ex)
                {
                    entry.Passed = false;
                    entry.Detail = ex.Message;
                    LiveSmokeTestSupport.Diag("SessionPool timeout: " + ex.Message);
                    return entry;
                }
                catch (OperationCanceledException)
                {
                    entry.Passed = false;
                    entry.Detail = ct.IsCancellationRequested
                        ? "Cancelled by caller."
                        : "Timed out after " +
                          ((long)TestTimeout.TotalSeconds)
                              .ToString(CultureInfo.InvariantCulture) + "s.";
                    LiveSmokeTestSupport.Diag("SessionPool canceled: " + entry.Detail);
                    return entry;
                }
                catch (Exception ex)
                {
                    entry.Passed = false;
                    entry.Detail = "Exception: " + ex.GetType().Name + ": " + ex.Message;
                    LiveSmokeTestSupport.Diag("SessionPool exception: " +
                        ex.GetType().Name + ": " + ex.Message);
                    return entry;
                }
                finally
                {
                    if (channel != null && !keepChannelAlive)
                    {
                        try { channel.Close(); }
                        catch (Exception closeEx)
                        {
                            EarlyLog.Write("SmokeTest", "Channel.Close threw: " +
                                closeEx.GetType().Name + ": " + closeEx.Message);
                        }
                    }
                    if (key != null)
                        key.Clear();
                    sw.Stop();
                    entry.Elapsed = sw.Elapsed;
                }
            }
        }

        public static void CloseCachedChannel()
        {
            lock (ChannelGate)
            {
                CloseCachedChannelUnderLock();
            }
        }

        private static global::Vianigram.MTProto.MtProtoChannel TryGetCachedChannel(
            ulong authKeyId)
        {
            lock (ChannelGate)
            {
                if (cachedChannel == null)
                    return null;

                if (cachedAuthKeyId == authKeyId && IsValidChannel(cachedChannel))
                    return cachedChannel;

                CloseCachedChannelUnderLock();
                return null;
            }
        }

        private static void CacheChannel(
            ulong authKeyId,
            global::Vianigram.MTProto.MtProtoChannel channel)
        {
            lock (ChannelGate)
            {
                if (cachedChannel != null && !object.ReferenceEquals(cachedChannel, channel))
                    CloseCachedChannelUnderLock();

                cachedAuthKeyId = authKeyId;
                cachedChannel = channel;
            }
        }

        private static void CloseCachedChannelUnderLock()
        {
            if (cachedChannel != null)
            {
                try { cachedChannel.Close(); }
                catch { }
            }
            cachedChannel = null;
            cachedAuthKeyId = 0UL;
        }

        private static bool IsValidChannel(
            global::Vianigram.MTProto.MtProtoChannel channel)
        {
            if (channel == null)
                return false;

            try
            {
                int poolSize = channel.PoolSize;
                return poolSize >= ExpectedMinPoolSize &&
                    poolSize <= ExpectedDefaultPoolSize &&
                    channel.SessionId != 0;
            }
            catch
            {
                return false;
            }
        }

        private static string DescribeInvalidChannel(
            global::Vianigram.MTProto.MtProtoChannel channel)
        {
            if (channel == null)
                return "MtProtoChannel.OpenAsync returned null.";

            try
            {
                int poolSize = channel.PoolSize;
                if (poolSize < ExpectedMinPoolSize ||
                    poolSize > ExpectedDefaultPoolSize)
                {
                    return "PoolSize out of expected band: got " +
                        poolSize.ToString(CultureInfo.InvariantCulture) +
                        ", expected [" +
                        ExpectedMinPoolSize.ToString(CultureInfo.InvariantCulture) +
                        ".." +
                        ExpectedDefaultPoolSize.ToString(CultureInfo.InvariantCulture) +
                        "].";
                }

                if (channel.SessionId == 0)
                {
                    return "Channel reports SessionId=0 after open (pool size=" +
                        poolSize.ToString(CultureInfo.InvariantCulture) + ").";
                }

                return "Channel failed validation.";
            }
            catch (Exception ex)
            {
                return "Channel validation threw " +
                    ex.GetType().Name + ": " + ex.Message;
            }
        }

        private static void PopulateSuccess(
            TestEntry entry,
            global::Vianigram.MTProto.MtProtoChannel channel,
            LiveAuthKeyMaterial key,
            string channelSource)
        {
            entry.Passed = true;
            entry.Detail = "PoolSize=" +
                channel.PoolSize.ToString(CultureInfo.InvariantCulture) +
                ", SessionId=0x" +
                channel.SessionId.ToString("x16", CultureInfo.InvariantCulture) +
                ", reused_auth_key_id=0x" +
                key.AuthKeyId.ToString("x16", CultureInfo.InvariantCulture) +
                ", key_source=" + (key.Source ?? "unknown") +
                ", channel_source=" + channelSource;
        }
    }
}
