// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: 2026 Angel Careaga <hello@angelcareaga.com>

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Vianigram.TlCodegen
{
    /// <summary>
    /// Emits a C++ header / source pair for a parsed <see cref="TlSchema"/>.
    /// The output uses <c>TlReader</c> / <c>TlWriter</c> primitives that live in
    /// <c>vianigram::tl::application</c>; this codegen only produces struct + IO methods.
    /// </summary>
    public sealed class TlEmitter
    {
        private readonly TlSchema _schema;
        private readonly string _headerPath;
        private readonly string _sourcePath;
        private readonly string _ns;
        private readonly int _layer;

        // Map from result-type name to its set of constructor structs (used to detect polymorphism).
        private readonly Dictionary<string, List<string>> _resultToCtors = new Dictionary<string, List<string>>(StringComparer.Ordinal);

        // Set of TL names that have an emitted struct (lowercased + as-written).
        private readonly HashSet<string> _emittedStructs = new HashSet<string>(StringComparer.Ordinal);

        // Set of TL names referenced by some field but never declared as a constructor.
        // These are abstract result types (e.g. auth.SentCodeType) — we emit a stub struct
        // so the generated C++ at least parses; the application layer is responsible for
        // polymorphic dispatch via TlReader::ReadAnyObject.
        private readonly HashSet<string> _abstractTypes = new HashSet<string>(StringComparer.Ordinal);

        public TlEmitter(TlSchema schema, string headerPath, string sourcePath, string ns, int layer)
        {
            _schema = schema ?? throw new ArgumentNullException(nameof(schema));
            _headerPath = headerPath;
            _sourcePath = sourcePath;
            _ns = string.IsNullOrEmpty(ns) ? "vianigram::tl" : ns;
            _layer = layer;
            BuildResultMap();
            BuildAbstractTypeSet();
        }

        public string EmitHeader()
        {
            var sb = new StringBuilder();
            EmitFileBanner(sb, isHeader: true);
            sb.AppendLine("#pragma once");
            sb.AppendLine();
            sb.AppendLine("#include <array>");
            sb.AppendLine("#include <cstdint>");
            sb.AppendLine("#include <string>");
            sb.AppendLine("#include <vector>");
            sb.AppendLine();
            // Forward-declare the canonical TlReader/TlWriter that live in
            // vianigram::tl. Application/ contains shim headers that re-export
            // these via `using`-declarations; we forward-declare the originals so
            // the alias and the forward declaration cannot collide.
            sb.AppendLine("// Forward declarations for the canonical TL reader/writer.");
            sb.AppendLine("// Full definitions in domain/tl_reader.h and domain/tl_writer.h.");
            sb.AppendLine("namespace vianigram { namespace tl {");
            sb.AppendLine("    class TlReader;");
            sb.AppendLine("    class TlWriter;");
            sb.AppendLine("} }");
            sb.AppendLine();

            OpenNamespace(sb);
            sb.AppendLine();
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "// Layer {0} schema generated by tools/tl-codegen.", _layer).AppendLine();
            // Use a static const at namespace scope; VS2013 lacks namespace-scope
            // constexpr support.
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "static const int kSchemaLayer = {0};", _layer).AppendLine();
            sb.AppendLine();

            // Bring TlReader/TlWriter into the generated namespace so the struct
            // declarations below can name them without qualification.
            sb.AppendLine("using ::vianigram::tl::TlReader;");
            sb.AppendLine("using ::vianigram::tl::TlWriter;");
            sb.AppendLine();

            // Emit forward declarations so types can reference each other regardless of order.
            sb.AppendLine("// ===== forward declarations =====");
            foreach (var t in _schema.Types)
            {
                if (t.IsPrimitiveAlias || t.IsVectorMagicLine) continue;
                sb.AppendFormat("struct {0};", CppStructName(t.Name)).AppendLine();
            }
            foreach (var f in _schema.Functions)
                sb.AppendFormat("struct {0};", CppStructName(f.Name)).AppendLine();
            foreach (var abs in _abstractTypes)
                sb.AppendFormat("struct {0};", CppStructName(abs)).AppendLine();
            sb.AppendLine();

            // Stub structs for abstract / polymorphic result types referenced by concrete
            // constructors but never declared themselves. The application layer is expected
            // to dispatch these via TlReader::ReadAnyObject (see docs/native-port/02-tl.md
            // section 4); this file only needs them to be complete C++ types so the concrete
            // structs that contain them as fields compile.
            if (_abstractTypes.Count > 0)
            {
                sb.AppendLine("// ===== abstract / polymorphic result types =====");
                foreach (var abs in _abstractTypes)
                {
                    sb.AppendFormat("// {0}: abstract result type. Resolved at read time via TlReader::ReadAnyObject.",
                        abs).AppendLine();
                    sb.AppendFormat("struct {0} {{", CppStructName(abs)).AppendLine();
                    sb.AppendLine("    uint32_t constructor_id = 0;");
                    sb.AppendLine("    std::vector<uint8_t> raw_payload;  // raw TL bytes — caller dispatches");
                    sb.AppendLine();
                    sb.AppendLine("    bool Serialize(TlWriter& w) const;");
                    sb.AppendFormat("    static bool Deserialize(TlReader& r, {0}& out);",
                        CppStructName(abs)).AppendLine();
                    sb.AppendLine("};");
                    sb.AppendLine();
                }
            }

            // Topological sort: a struct that contains another struct *by value*
            // must be defined AFTER its dependency, otherwise the field type is
            // incomplete at the point of declaration. Functions never appear as
            // field types (they're RPC-only), so they always go last.
            var sortedTypes = TopoSortTypes();

            sb.AppendLine("// ===== types =====");
            foreach (var t in sortedTypes)
            {
                EmitTypeStruct(sb, t.Name, t.ConstructorId, t.Fields, t.ResultType, isFunction: false);
                sb.AppendLine();
            }

            sb.AppendLine("// ===== functions (RPC methods) =====");
            foreach (var f in _schema.Functions)
            {
                EmitTypeStruct(sb, f.Name, f.ConstructorId, f.Arguments, f.ResultType, isFunction: true);
                sb.AppendLine();
            }

            sb.AppendLine("// Registers every constructor in this layer with the runtime schema.");
            sb.AppendLine("// Implementation lives in the matching .cpp; passing TlSchema by pointer avoids");
            sb.AppendLine("// pulling the aggregate header into every translation unit that just wants the structs.");
            sb.AppendLine("namespace runtime { class TlSchema; }");
            sb.AppendFormat("void RegisterAllLayer{0}(runtime::TlSchema* schema);", _layer).AppendLine();
            sb.AppendLine();

            CloseNamespace(sb);
            return sb.ToString();
        }

        public string EmitSource()
        {
            var sb = new StringBuilder();
            EmitFileBanner(sb, isHeader: false);

            string headerName = System.IO.Path.GetFileName(_headerPath);
            sb.AppendFormat("#include \"{0}\"", headerName).AppendLine();
            sb.AppendLine();
            // Pull in the canonical reader/writer definitions. The application/
            // shim headers re-export the same types under
            // vianigram::tl::application::* — kept around for legacy callers but
            // not used by codegen output anymore.
            sb.AppendLine("#include \"../../domain/tl_reader.h\"");
            sb.AppendLine("#include \"../../domain/tl_writer.h\"");
            sb.AppendLine();

            OpenNamespace(sb);
            sb.AppendLine();

            // Stub Serialize/Deserialize for abstract types — the MVP just round-trips the
            // raw payload bytes. The application layer is responsible for actually dispatching
            // these via the TL type registry when the wire data is finally consumed.
            //
            // For abstract types we emit a "boxed peek + skip" stub:
            //   - Serialize writes the constructor_id then dumps raw_payload as TL bytes.
            //   - Deserialize peeks the constructor_id (rolls back) and stores it; the
            //     payload is left for the application layer to dispatch into a concrete
            //     constructor via the runtime registry. This keeps the generated header
            //     self-contained and avoids hard-wiring polymorphic dispatch into codegen.
            foreach (var abs in _abstractTypes)
            {
                string s = CppStructName(abs);
                sb.AppendFormat("bool {0}::Serialize(TlWriter& w) const {{", s).AppendLine();
                sb.AppendLine("    w.WriteUInt32(constructor_id);");
                sb.AppendLine("    if (!raw_payload.empty()) w.WriteBytes(raw_payload.data(), raw_payload.size());");
                sb.AppendLine("    return true;");
                sb.AppendLine("}");
                sb.AppendLine();
                sb.AppendFormat("bool {0}::Deserialize(TlReader& r, {0}& out) {{", s).AppendLine();
                sb.AppendLine("    // Peek the boxed constructor_id; concrete dispatch is the caller's job.");
                sb.AppendLine("    if (!r.ReadUInt32(out.constructor_id)) return false;");
                sb.AppendLine("    // The remaining payload is intentionally not consumed here — the");
                sb.AppendLine("    // application-layer registry must read the concrete fields.");
                sb.AppendLine("    out.raw_payload.clear();");
                sb.AppendLine("    return true;");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            foreach (var t in _schema.Types)
            {
                if (t.IsPrimitiveAlias || t.IsVectorMagicLine) continue;
                EmitSerializeImpl(sb, t.Name, t.ConstructorId, t.Fields);
                EmitDeserializeImpl(sb, t.Name, t.ConstructorId, t.Fields);
            }
            foreach (var f in _schema.Functions)
            {
                EmitSerializeImpl(sb, f.Name, f.ConstructorId, f.Arguments);
                EmitDeserializeImpl(sb, f.Name, f.ConstructorId, f.Arguments);
            }

            // RegisterAllLayer<N>: stubbed registration. The schema aggregate exposes a
            // void(TlSchema&, uint32_t) overload — this list keeps codegen output minimal.
            // Take the parameter by pointer so we don't need the complete TlSchema
            // type at this translation unit (`(void)*p` would require it).
            sb.AppendFormat("void RegisterAllLayer{0}(runtime::TlSchema* schema) {{", _layer).AppendLine();
            sb.AppendLine("    // The runtime registration table is wired up by the loader use case.");
            sb.AppendLine("    // We intentionally keep this body empty in the MVP — the loader inspects");
            sb.AppendLine("    // each emitted struct via templates rather than a runtime table.");
            sb.AppendLine("    (void)schema;  // pointer is fine even with incomplete TlSchema");
            sb.AppendLine("}");
            sb.AppendLine();

            CloseNamespace(sb);
            return sb.ToString();
        }

        // ---------------------------------------------------------------
        // Header struct emission
        // ---------------------------------------------------------------

        private void EmitTypeStruct(StringBuilder sb, string tlName, uint ctorId, List<TlField> fields,
            string resultType, bool isFunction)
        {
            sb.AppendFormat("// {0}#{1:x8}", tlName, ctorId).AppendLine();
            if (isFunction) sb.AppendFormat("// returns: {0}", resultType).AppendLine();
            sb.AppendFormat("struct {0} {{", CppStructName(tlName)).AppendLine();
            // v120 (VS2013) supports static const integral with in-class initializer.
            sb.AppendFormat("    static const uint32_t kConstructorId = 0x{0:x8}u;", ctorId).AppendLine();

            foreach (var field in fields)
            {
                string cppType = MapFieldTypeToCpp(field.Type);
                string comment = field.IsOptional
                    ? string.Format(CultureInfo.InvariantCulture,
                        "  // valid if ({0} & (1u << {1}))", field.FlagsFieldName, field.FlagBit.Value)
                    : string.Empty;
                sb.AppendFormat("    {0} {1};{2}", cppType, CppFieldName(field.Name), comment).AppendLine();
            }

            sb.AppendLine();
            sb.AppendLine("    bool Serialize(TlWriter& w) const;");
            sb.AppendFormat("    static bool Deserialize(TlReader& r, {0}& out);", CppStructName(tlName)).AppendLine();
            sb.AppendLine("};");
        }

        // ---------------------------------------------------------------
        // Source method emission
        // ---------------------------------------------------------------

        private void EmitSerializeImpl(StringBuilder sb, string tlName, uint ctorId, List<TlField> fields)
        {
            string structName = CppStructName(tlName);
            sb.AppendFormat("bool {0}::Serialize(TlWriter& w) const {{", structName).AppendLine();
            sb.AppendLine("    w.WriteUInt32(kConstructorId);");
            foreach (var field in fields)
                sb.Append(EmitWriteField(field, indent: "    "));
            sb.AppendLine("    return true;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private void EmitDeserializeImpl(StringBuilder sb, string tlName, uint ctorId, List<TlField> fields)
        {
            string structName = CppStructName(tlName);
            sb.AppendFormat("bool {0}::Deserialize(TlReader& r, {0}& out) {{", structName).AppendLine();
            sb.AppendLine("    uint32_t ctor = 0;");
            sb.AppendLine("    if (!r.ReadUInt32(ctor)) return false;");
            sb.AppendLine("    if (ctor != kConstructorId) return false;");
            foreach (var field in fields)
                sb.Append(EmitReadField(field, indent: "    "));
            sb.AppendLine("    return true;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private string EmitWriteField(TlField field, string indent)
        {
            // A flags.N?true field has no wire encoding — its presence is the value.
            // Skip emitting code entirely; the bit in `flags` already carries the signal.
            if (field.IsOptional && IsTrueType(field.Type))
                return $"{indent}// {field.Name}: flags.{field.FlagBit.Value}?true (presence-only, no wire bytes)\n";

            string fname = CppFieldName(field.Name);
            if (field.IsOptional)
            {
                string body = EmitWriteValue("this->" + fname, field.Type, indent + "    ");
                var sb = new StringBuilder();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}if (this->{1} & (1u << {2})) {{", indent, CppFieldName(field.FlagsFieldName), field.FlagBit.Value).AppendLine();
                sb.Append(body);
                sb.AppendFormat("{0}}}", indent).AppendLine();
                return sb.ToString();
            }
            return EmitWriteValue("this->" + fname, field.Type, indent);
        }

        private string EmitReadField(TlField field, string indent)
        {
            if (field.IsOptional && IsTrueType(field.Type))
                return $"{indent}// {field.Name}: flags.{field.FlagBit.Value}?true (presence-only, no wire bytes)\n";

            string fname = CppFieldName(field.Name);
            if (field.IsOptional)
            {
                string body = EmitReadValue("out." + fname, field.Type, indent + "    ");
                var sb = new StringBuilder();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}if (out.{1} & (1u << {2})) {{", indent, CppFieldName(field.FlagsFieldName), field.FlagBit.Value).AppendLine();
                sb.Append(body);
                sb.AppendFormat("{0}}}", indent).AppendLine();
                return sb.ToString();
            }
            return EmitReadValue("out." + fname, field.Type, indent);
        }

        private static bool IsTrueType(TlFieldType type)
        {
            return type != null && !type.IsVector && (type.TypeName == "true" || type.TypeName == "True");
        }

        private string EmitWriteValue(string accessor, TlFieldType type, string indent)
        {
            if (type.TypeName == "#")
                return string.Format(CultureInfo.InvariantCulture,
                    "{0}w.WriteUInt32({1});\n", indent, accessor);

            if (type.IsVector)
            {
                var sb = new StringBuilder();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}w.WriteUInt32(0x1cb5c415u);", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}w.WriteUInt32(static_cast<uint32_t>({1}.size()));", indent, accessor).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}for (const auto& __item : {1}) {{", indent, accessor).AppendLine();
                sb.Append(EmitWriteValue("__item", type.Inner, indent + "    "));
                sb.AppendFormat("{0}}}", indent).AppendLine();
                return sb.ToString();
            }

            string prim = MapPrimitive(type.TypeName);
            if (prim != null)
            {
                switch (prim)
                {
                    case "int":     return Line(indent, $"w.WriteInt32({accessor});");
                    case "long":    return Line(indent, $"w.WriteInt64({accessor});");
                    case "double":  return Line(indent, $"w.WriteDouble({accessor});");
                    case "string":  return Line(indent, $"w.WriteString({accessor});");
                    // TlWriter::WriteBytes takes (const uint8_t*, size_t).
                    case "bytes":   return Line(indent, $"w.WriteBytes({accessor}.data(), {accessor}.size());");
                    case "int128":  return Line(indent, $"w.WriteInt128({accessor}.data());");
                    case "int256":  return Line(indent, $"w.WriteInt256({accessor}.data());");
                    case "true":    return Line(indent, "/* implicit true: no wire bytes */");
                    case "bool":    return Line(indent, $"w.WriteBool({accessor});");
                }
            }

            // Boxed object reference — recurse via Serialize().
            return Line(indent, $"if (!{accessor}.Serialize(w)) return false;");
        }

        private string EmitReadValue(string accessor, TlFieldType type, string indent)
        {
            if (type.TypeName == "#")
                return Line(indent, $"if (!r.ReadUInt32({accessor})) return false;");

            if (type.IsVector)
            {
                var sb = new StringBuilder();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}{{", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    uint32_t __magic = 0;", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    if (!r.ReadUInt32(__magic) || __magic != 0x1cb5c415u) return false;", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    uint32_t __count = 0;", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    if (!r.ReadUInt32(__count)) return false;", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    {1}.resize(__count);", indent, accessor).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    for (uint32_t __i = 0; __i < __count; ++__i) {{", indent).AppendLine();
                sb.Append(EmitReadValue(accessor + "[__i]", type.Inner, indent + "        "));
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}    }}", indent).AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0}}}", indent).AppendLine();
                return sb.ToString();
            }

            string prim = MapPrimitive(type.TypeName);
            if (prim != null)
            {
                switch (prim)
                {
                    case "int":     return Line(indent, $"if (!r.ReadInt32({accessor})) return false;");
                    case "long":    return Line(indent, $"if (!r.ReadInt64({accessor})) return false;");
                    case "double":  return Line(indent, $"if (!r.ReadDouble({accessor})) return false;");
                    case "string":  return Line(indent, $"if (!r.ReadString({accessor})) return false;");
                    case "bytes":   return Line(indent, $"if (!r.ReadBytes({accessor})) return false;");
                    case "int128":  return Line(indent, $"if (!r.ReadInt128({accessor}.data())) return false;");
                    case "int256":  return Line(indent, $"if (!r.ReadInt256({accessor}.data())) return false;");
                    case "true":    return Line(indent, "/* implicit true: no wire bytes */");
                    case "bool":    return Line(indent, $"if (!r.ReadBool({accessor})) return false;");
                }
            }

            // Boxed object reference — recurse via static Deserialize.
            return Line(indent, $"if (!{TypeRefAsCppName(type)}::Deserialize(r, {accessor})) return false;");
        }

        // ---------------------------------------------------------------
        // Helpers
        // ---------------------------------------------------------------

        private static string Line(string indent, string body)
        {
            return indent + body + "\n";
        }

        private void EmitFileBanner(StringBuilder sb, bool isHeader)
        {
            sb.AppendLine("// =====================================================================");
            sb.AppendLine("// Auto-generated by tools/tl-codegen. DO NOT EDIT.");
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "// Layer: {0}", _layer).AppendLine();
            sb.AppendLine("// =====================================================================");
            sb.AppendLine();
        }

        private void OpenNamespace(StringBuilder sb)
        {
            foreach (var part in _ns.Split(new[] { "::" }, StringSplitOptions.RemoveEmptyEntries))
                sb.AppendFormat("namespace {0} {{", part).AppendLine();
        }

        private void CloseNamespace(StringBuilder sb)
        {
            int depth = _ns.Split(new[] { "::" }, StringSplitOptions.RemoveEmptyEntries).Length;
            for (int i = 0; i < depth; i++) sb.AppendLine("}");
        }

        private void BuildResultMap()
        {
            foreach (var t in _schema.Types)
            {
                if (t.IsPrimitiveAlias || t.IsVectorMagicLine || string.IsNullOrEmpty(t.ResultType)) continue;
                if (!_resultToCtors.TryGetValue(t.ResultType, out var list))
                    _resultToCtors[t.ResultType] = list = new List<string>();
                list.Add(t.Name);
                _emittedStructs.Add(t.Name);
            }
            foreach (var f in _schema.Functions)
                _emittedStructs.Add(f.Name);
        }

        // Walks every field type reference and records the names that are not primitives,
        // not vectors/inner, and that don't correspond to an emitted struct. Result types on
        // the right-hand side of `=` are also tracked so abstract names like `auth.SentCode`
        // get a placeholder.
        private void BuildAbstractTypeSet()
        {
            void Visit(TlFieldType ft)
            {
                if (ft == null) return;
                if (ft.IsVector) { Visit(ft.Inner); return; }
                if (ft.TypeName == "#") return;
                if (MapPrimitive(ft.TypeName) != null) return;
                if (ResolveStructName(ft.TypeName) == null)
                    _abstractTypes.Add(ft.TypeName);
            }

            foreach (var t in _schema.Types)
            {
                if (t.IsPrimitiveAlias || t.IsVectorMagicLine) continue;
                foreach (var f in t.Fields) Visit(f.Type);
            }
            foreach (var fn in _schema.Functions)
                foreach (var f in fn.Arguments) Visit(f.Type);
        }

        // Convert a TL identifier ("auth.sentCode") to a C++ struct name ("Tl_auth_sentCode").
        public static string CppStructName(string tlName)
        {
            var sb = new StringBuilder("Tl_");
            sb.Append(tlName.Replace('.', '_'));
            return sb.ToString();
        }

        // Resolves a referenced TL type name to the actual emitted struct name, accounting for
        // Telegram's convention that the boxed result type starts with an uppercase letter
        // (e.g. CodeSettings) while the constructor starts lowercase (e.g. codeSettings).
        // Returns null if no struct matches; callers fall back to the stub-struct path.
        private string ResolveStructName(string tlName)
        {
            if (_emittedStructs.Contains(tlName)) return tlName;

            // Try lower/upper-casing the last segment after '.'
            int dot = tlName.LastIndexOf('.');
            string head = dot >= 0 ? tlName.Substring(0, dot + 1) : string.Empty;
            string tail = dot >= 0 ? tlName.Substring(dot + 1) : tlName;
            if (tail.Length > 0)
            {
                string lowered = head + char.ToLowerInvariant(tail[0]) + tail.Substring(1);
                if (_emittedStructs.Contains(lowered)) return lowered;
                string upped = head + char.ToUpperInvariant(tail[0]) + tail.Substring(1);
                if (_emittedStructs.Contains(upped)) return upped;
            }
            return null;
        }

        private static string CppFieldName(string tlName)
        {
            // Field names map 1:1 except dots become underscores. Reserved C++ words get a trailing underscore.
            string mapped = tlName.Replace('.', '_');
            if (IsCppReserved(mapped)) mapped += "_";
            return mapped;
        }

        private static bool IsCppReserved(string n)
        {
            switch (n)
            {
                case "class": case "struct": case "union": case "namespace":
                case "template": case "typename": case "operator":
                case "this": case "new": case "delete": case "return":
                case "void": case "int": case "long": case "short": case "char":
                case "float": case "double": case "bool": case "true": case "false":
                case "default": case "switch": case "case": case "if": case "else":
                case "while": case "for": case "do": case "break": case "continue":
                case "private": case "public": case "protected": case "virtual":
                case "static": case "extern": case "inline": case "register":
                case "const": case "volatile": case "signed": case "unsigned":
                case "auto": case "sizeof": case "typedef": case "enum":
                case "goto": case "throw": case "try": case "catch":
                    return true;
                default: return false;
            }
        }

        private string MapFieldTypeToCpp(TlFieldType type)
        {
            if (type.TypeName == "#") return "uint32_t";

            if (type.IsVector)
                return "std::vector<" + MapFieldTypeToCpp(type.Inner) + ">";

            string prim = MapPrimitive(type.TypeName);
            if (prim != null)
            {
                switch (prim)
                {
                    case "int":    return "int32_t";
                    case "long":   return "int64_t";
                    case "double": return "double";
                    case "string": return "std::string";
                    case "bytes":  return "std::vector<uint8_t>";
                    case "int128": return "std::array<uint8_t, 16>";
                    case "int256": return "std::array<uint8_t, 32>";
                    case "true":   return "bool";
                    case "bool":   return "bool";
                }
            }

            // Boxed object — emit struct name. Telegram sometimes capitalises the result type
            // (e.g. auth.SentCodeType vs auth.sentCodeType); when the schema provides a
            // matching constructor we use that, otherwise we fall back to a stub struct
            // (emitted in the header) so the C++ at least parses.
            string resolved = ResolveStructName(type.TypeName) ?? type.TypeName;
            return CppStructName(resolved);
        }

        private string TypeRefAsCppName(TlFieldType type) => MapFieldTypeToCpp(type);

        // Topologically sort the schema's concrete types so that a struct's
        // value-typed dependencies are emitted before it. Cycles (rare in TL,
        // but possible via abstract polymorphism) are broken by emitting the
        // remaining nodes in original order; the abstract stub types they
        // resolve through are already defined up top, so the cycle is purely
        // through pointer-like reference fields.
        private List<TlType> TopoSortTypes()
        {
            // Index concrete types by name.
            var byName = new Dictionary<string, TlType>(StringComparer.Ordinal);
            foreach (var t in _schema.Types)
            {
                if (t.IsPrimitiveAlias || t.IsVectorMagicLine) continue;
                byName[t.Name] = t;
            }

            // Build a dependency edge t -> referenced concrete type names.
            // Vector elements are NOT dependencies (they're stored as
            // std::vector<T>, which only needs T to be complete at the point
            // of std::vector<T>::operator[]; for declaration the forward
            // declaration is sufficient because std::vector<incomplete> is
            // technically UB pre-C++17 — but VS2013 happens to accept it
            // because <vector> only instantiates members lazily). To stay safe,
            // we DO treat vector inner types as dependencies — better to over-
            // order than to risk a hidden incomplete-type bug.
            //
            // Optional-flagged fields ARE dependencies because the C++ field is
            // declared at the struct-body level regardless of the optional bit.
            var dependsOn = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
            foreach (var t in byName.Values)
            {
                var deps = new HashSet<string>(StringComparer.Ordinal);
                foreach (var f in t.Fields) CollectFieldDeps(f.Type, deps, byName);
                dependsOn[t.Name] = deps;
            }

            // Standard Kahn's-algorithm topological sort with deterministic order
            // (we iterate the original schema order to break ties).
            var result = new List<TlType>(byName.Count);
            var emitted = new HashSet<string>(StringComparer.Ordinal);
            var stack = new List<string>();

            void Visit(string name)
            {
                if (emitted.Contains(name)) return;
                if (stack.Contains(name)) return;  // cycle — break here
                stack.Add(name);
                if (dependsOn.TryGetValue(name, out var deps))
                {
                    foreach (var dep in deps) Visit(dep);
                }
                stack.RemoveAt(stack.Count - 1);
                emitted.Add(name);
                if (byName.TryGetValue(name, out var t)) result.Add(t);
            }

            foreach (var t in _schema.Types)
            {
                if (t.IsPrimitiveAlias || t.IsVectorMagicLine) continue;
                Visit(t.Name);
            }
            return result;
        }

        // Walk a type-ref (vector / boxed) collecting concrete type-name dependencies.
        private void CollectFieldDeps(TlFieldType ft, HashSet<string> sink,
            Dictionary<string, TlType> byName)
        {
            if (ft == null) return;
            if (ft.IsVector) { CollectFieldDeps(ft.Inner, sink, byName); return; }
            if (ft.TypeName == "#") return;
            if (MapPrimitive(ft.TypeName) != null) return;
            string resolved = ResolveStructName(ft.TypeName);
            if (resolved != null && byName.ContainsKey(resolved))
                sink.Add(resolved);
            // Else: abstract type — already defined at the top of the header,
            // no ordering constraint among concrete types.
        }

        // Recognises the TL primitive types. Returns the canonical primitive name or null.
        private static string MapPrimitive(string tlTypeName)
        {
            switch (tlTypeName)
            {
                case "int":    case "Int":    return "int";
                case "long":   case "Long":   return "long";
                case "double": case "Double": return "double";
                case "string": case "String": return "string";
                case "bytes":  case "Bytes":  return "bytes";
                case "int128": case "Int128": return "int128";
                case "int256": case "Int256": return "int256";
                case "true":   case "True":   return "true";
                // Bool is technically a boxed type with two constructors, but the
                // reader/writer expose first-class WriteBool/ReadBool primitives that
                // emit the canonical 0x997275b5 / 0xbc799737 marker. Treat it as a
                // primitive in the codegen so generated code stays compact and
                // bypasses the abstract-type peek-only stub.
                case "Bool":                  return "bool";
                default: return null;
            }
        }
    }
}
